### ISSUE TITLE
Shopping Cart and User profile

### ISSUE THREAD

**Issue by jeffliang0318** [jeffliang0318/Jtsy#10]
- [x] Backend: DB, model, controller, views

- [x]  Redux Loop: ajax, actions, reducer

- [x]  Presentational Components

- [x]  Adequate styling

- [ ]  Smooth, bug-free navigation

- [x]  Seeded with info to demonstrate this feature

- [x] User need to login to add products to cart

- [x] User can not add their own product to their cart

- [x] User profile can see the product user sell and the items on their shopping cart

**Comment by xnanodax** [comment]
- [ ] When removing an item from the cart, the user should stay in the cart page instead of being redirected to `/`
- [ ] I can see my user profile but I can't see other people's profile. I suggest adding a username of the person selling the item. You can then click on the username if you wanted to buy more items from their user profile page.

**Comment by xnanodax** [comment]
The core functionality of the cart is there :) This issue is closed!

If you come back to this project, I would create the user show page!
