### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by jeffliang0318** [jeffliang0318/Jtsy#8]
- [x]  Backend: DB, model, controller, views

- [x] Redux Loop: ajax, actions, reducers

- [x] Presentational Components

- [x] Demo User Added

- [x] Styling

- [x] Smooth, bug free navigation
  - [x] Login errors clears when switching from login form to sign up form (and vice-versa)

- [x] Adequate and appropriate seeds

**Comment by jeffliang0318** [comment]
Should be all good, will working on more styling later

**Comment by xnanodax** [comment]
- [x] Also, if I were to acccess a bogus page like localhost:3000/jdfklajsdklfjalksdf, I should be redirected to a page like "localhost:3000/" hint: redirect

**Comment by jeffliang0318** [comment]
update: redirect to index page

**Comment by xnanodax** [comment]
Great work so far :)! 

- [ ] When hovering over a link or button, the pointer should turn into a pointing hand instead of the default mouse cursor.
- [x] Render the errors in a different color. They are currently black.
- [x] Add more padding in the modal session/login form
- [ ] Typically modal have a "X" on the corner to close the modal.
- [x] On the register page, the login button shouldn't be next to the Register header. It is confusing for the user what this page is doing. 
![screen shot 2018-04-06 at 11 45 04 am](https://user-images.githubusercontent.com/20424731/38438678-078a70d6-3990-11e8-8291-d0962262b73c.png)

**Comment by xnanodax** [comment]
- [x] When logging in, I currently see this error on the console:
![screen shot 2018-04-11 at 11 33 04 am](https://user-images.githubusercontent.com/20424731/38636107-2d55eb8e-3d7c-11e8-9f12-eabd04e3a453.png)
- [x] Receiving a 500 level error when using the demo login.
- [x] Cannot log out of the site.
- [x] Sign in form should look more similar to the Etsy's. You can ignore the facebook google login buttons.
![screen shot 2018-04-11 at 11 46 37 am](https://user-images.githubusercontent.com/20424731/38636793-1cac94c0-3d7e-11e8-9b9a-0c10d365846b.png)
![screen shot 2018-04-11 at 11 47 00 am](https://user-images.githubusercontent.com/20424731/38636796-1deb6956-3d7e-11e8-86aa-9058551318b5.png)

**Comment by xnanodax** [comment]
Hey Jeff :) Let's update some of the styling and then we can close off this issue! Thank you!

**Comment by jeffliang0318** [comment]
I think it is better now...

**Comment by xnanodax** [comment]
Great work :)! Still some styling notes outlined above in case you want to come back and refactor. Great styling updates :)!
